apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metabase-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-metabase'
    spec:
      source:
        repoURL: https://github.com/MSBarbieri/argocd-application-sets.git
        targetRevision: HEAD
        path: deploys/metabase
