apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgres-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-postgres'
    spec:
      source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 11.1.24
        chart: postgresql
        helm:
          valueFiles:
            - values.yaml
          parameters:
          - name: global.postgresql.auth.database
            value: '{{cluster}}'
