apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
spec:
  template:
    metadata:
      name: '{{cluster}}-sealed-secrets'
    spec:
      project: default
      source:
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.1.5
        chart: sealed-secrets
